### ISSUE TITLE
[feature] make it work with http URL

### ISSUE THREAD

**Issue by ebuildy** [mogensen/kubernetes-split-yaml#10]
for lazy people like me, something like 

```
kubernetes-split-yaml https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml
```

**Comment by elzapp** [comment]
When I'm lazy, I pipe curl to kubernetes-split-yaml
```
curl -L https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml | kubernetes-split-yaml -
```

**Comment by mogensen** [comment]
Hehe. I love lazy people. 
@ebuildy I will keep the feature request in mind for the future. But I think @elzapp has a better way for now. :)

**Comment by ebuildy** [comment]
absolutely !

(I hate pipe usually , because this is not compatible with container and some other tool but I will wrap this into a shell file)
